### ISSUE TITLE
ParseTxt modifying HTTParty's SupportedFormats conflicts with other libraries

### ISSUE THREAD

**Issue by FooBarWidget** [patchfx/fastspring-saasy#4]
The Gibbon gem uses HTTParty as well and calls "format :plain". Normally, HTTParty maps text/plain to :plain, but fastspring-saasy changes it to :txt. This causes Gibbon's call to "format :plain" to fail. I cannot use Gibbon and fastspring-saasy together.

**Comment by patchfx** [comment]
Fixed in https://github.com/patchfx/fastspring-saasy/commit/b614c55c4510483735768c44f9f63ad10e6b3d0c
